*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_T
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A11_TTOP.
*INCLUDE BC414_TRAVELAG_TTOP.
INCLUDE ZTRAVELAG_A11_TF01.
*INCLUDE BC414_TRAVELAG_TF01.
INCLUDE ZTRAVELAG_A11_TO01.
*INCLUDE BC414_TRAVELAG_TO01.
INCLUDE ZTRAVELAG_A11_TI01.
*INCLUDE BC414_TRAVELAG_TI01.
INCLUDE ZTRAVELAG_A11_TE01.
*INCLUDE BC414_TRAVELAG_TE01.
